version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: magic-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: magic
      MYSQL_DATABASE: magicbutton
      MYSQL_USER: magicuser
      MYSQL_PASSWORD: magicpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ['--default-authentication-plugin=mysql_native_password']

volumes:
  db_data:
